# config/routes.yaml

app_home:
    path: /
    controller: App\Controller\JobEntryController::index

app_about:
    path: /about
    controller: App\Controller\JobEntryController::about

admin_supplier:
    path: /supplier
    controller: App\Controller\SupplierController::index
